# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-26 20:41
# flake8: noqa
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multigtfs', '0002_add_on_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequency',
            name='exact_times',
            field=models.CharField(blank=True, choices=[('0', 'Trips are not exactly scheduled'), ('1', 'Trips are exactly scheduled from start time')], help_text='Should frequency-based trips be exactly scheduled?', max_length=1),
        ),
    ]
